'use client';
/* eslint-disable @next/next/no-html-link-for-pages */
import { useEffect, useState } from 'react';
import { ownerHeaders } from '@/lib/owner-id';

export default function ProfilePage() {
  const [data, setData] = useState<any>(null);
  const [feedback, setFeedback] = useState<string>('');
  useEffect(() => { fetch('/api/profile', { headers: ownerHeaders() }).then((r) => r.json()).then(setData).catch(() => undefined); }, []);
  if (!data) return <main className="min-h-screen p-8 text-sm">正在加载思维画像…</main>;
  const p = data.thinkingProfile;
  return <main className="min-h-screen bg-surface p-6 sm:p-10"><div className="max-w-3xl mx-auto space-y-6"><a href="/" className="text-sm text-brand">返回知研</a><h1 className="text-2xl font-semibold">我的思维画像</h1>{p ? <><section className="rounded-xl border border-line bg-surface-elevated p-5"><div className="flex justify-between"><h2 className="text-xl font-semibold">{p.name}</h2><span className="font-mono text-brand">{p.code}</span></div><p className="text-sm text-content-secondary mt-2">{p.sampleSize} 次决策 · 置信度 {Math.round(p.confidence * 100)}%</p><div className="grid sm:grid-cols-2 gap-3 mt-4">{p.axes.map((a: any) => <div key={a.key} className="border border-line rounded-lg p-3"><div className="text-xs text-content-secondary">{a.key}</div><div className="text-sm font-medium mt-1">{a.score >= 0 ? a.positive : a.negative}</div></div>)}</div></section><section className="rounded-xl border border-line bg-surface-elevated p-5"><h2 className="font-semibold mb-3">思维优劣势</h2><p className="text-sm text-emerald-700">优势：{p.strengths.join('；')}</p><p className="text-sm text-amber-700 mt-2">可能盲区：{p.blindSpots.join('；')}</p>{data.aiReview && <pre className="mt-4 whitespace-pre-wrap text-xs text-content-secondary">{JSON.stringify(data.aiReview, null, 2)}</pre>}<div className="mt-5 flex gap-2"><button onClick={() => { setFeedback('accurate'); void fetch('/api/profile', { method: 'PATCH', headers: { ...ownerHeaders(), 'Content-Type': 'application/json' }, body: JSON.stringify({ rating: 'accurate' }) }); }} className="px-3 py-2 rounded-lg border border-line text-xs">点评准确</button><button onClick={() => { setFeedback('partial'); void fetch('/api/profile', { method: 'PATCH', headers: { ...ownerHeaders(), 'Content-Type': 'application/json' }, body: JSON.stringify({ rating: 'partial' }) }); }} className="px-3 py-2 rounded-lg border border-line text-xs">部分准确</button><button onClick={() => { setFeedback('inaccurate'); void fetch('/api/profile', { method: 'PATCH', headers: { ...ownerHeaders(), 'Content-Type': 'application/json' }, body: JSON.stringify({ rating: 'inaccurate' }) }); }} className="px-3 py-2 rounded-lg border border-line text-xs">不太准确</button></div>{feedback && <p className="text-xs text-content-secondary mt-2">已记录反馈</p>}</section></> : <p className="text-sm text-content-secondary">完成更多推演后，这里会生成你的思维画像。</p>}</div></main>;
}
